account/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as pass_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.UserLogIn.as_view(), name='log in'),
    path('logout', views.UserLogOut.as_view(), name='log out'),
    path('register', views.UserRegister.as_view(), name='register'),
    path(
        'activate/(?P<uidb64>[0-9A-Za-z_\\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate,
        name='activate'),
    re_path(r'profile/(?P<id>[0-9]+)/(?P<username>[-\w]+)/', views.user_profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit profile'),
    path(
        "password_reset/",
        pass_views.PasswordResetView.as_view(
            template_name="account/forgotpassword.html",
            email_template_name="account/password_reset_email.html",
            success_url=reverse_lazy("account:password_reset_done")
        ),
        name="password_reset"),
    path(
        "password_reset/done/",
        pass_views.PasswordResetDoneView.as_view(template_name="account/reset_password_done.html"),
        name="password_reset_done",),
    path(
        "reset/<uidb64>/<token>/",
        pass_views.PasswordResetConfirmView.as_view(
            template_name="account/reset-password.html",
            success_url=reverse_lazy("account:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        pass_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
        name="password_reset_complete",),
    path('follow/<int:id>/', views.user_follow, name='follow')
]

home/urls.py
from django.urls import path
from .views import HomePage

app_name = 'home'

urlpatterns = [
    path('', HomePage.as_view(), name='home')
]

tipHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('videos/', include('videos.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path, re_path
from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.VideoList.as_view(), name='all videos'),
    re_path(r'video_detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', views.video_detail, name='video detail'),
    re_path(r'category_detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', views.CategoryDetail.as_view(), name='category detail'),
    path('video_like/<int:id>', views.video_like, name='video like'),
    path("search_result/", views.SearchResult.as_view(), name='search result'),
    path("favorites/", views.FavoriteVideos.as_view(), name='favorites'),
    re_path(r'delete_comment/(?P<pk>[0-9]+)/', views.comment_delete, name='delete comment'),
    re_path(r"read_notification/(?P<notif_id>[0-9]+)/", views.read_notification, name='read_notification'),
]

templates/includes/footer.html
{% load static %}
    <!-- footer -->
    <footer>
        <div class="container-fluid py-5">

            <section class="row d-flex align-items-baseline footer-items">
                <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                    <div>
                        <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                        <a href="">
                            <p>راهنمای استفاده</p>
                        </a>
                        <a href="">
                            <p>سوالات متداول </p>
                        </a>
                        <a href="">
                            <p>قوانین و مقررات </p>
                        </a>
                        <a href="">
                            <p>پیشنهاد آموزش </p>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                    <div>
                        <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                        <a href="">
                            <p>راهنمای استفاده</p>
                        </a>
                        <a href="">
                            <p>سوالات متداول </p>
                        </a>
                        <a href="">
                            <p>قوانین و مقررات </p>
                        </a>
                        <a href="">
                            <p>پیشنهاد آموزش </p>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                    <div>
                        <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                        <a href="">
                            <p>مستندات جنگو</p>
                        </a>
                        <a href="">
                            <p>آموزش دارت</p>
                        </a>
                        <a href="">
                            <p>خلاصه کتاب‌های پایتون</p>
                        </a>
                        <a href="">
                            <p>چند نکته ی پایتونی</p>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                    <div>
                        <h6 class="mb-3 text-white"><span class="border-bottom">تماس با ما</span></h6>
                        <a href="" class="">
                            <img src="{% static 'image/f1.svg' %}" alt="">
                            {{ contact_info.location }}
                        </a>
                        <a href="" class="">
                            <img src="{% static 'image/f2.svg' %}" alt="">
                            پشتیبانی: {{ contact_info.support }}
                        </a>
                        <a href="" class="">
                            <img src="{% static 'image/f4.svg' %}" alt="">
                            {{ contact_info.email }}
                        </a>

                        <button class="footer-btn my-3">ارسال پیام</button>

                        <div class="social-media d-flex align-items-center flex-wrap ">
                            {% if contact_info.instagram %}
                                <a href="{{ contact_info.instagram }}"> <i class="fa fa-instagram"></i></a>
                            {% endif %}
                            {% if contact_info.telegram %}
                                <a href="{{ contact_info.telegram }}"> <i class="fa fa-telegram"></i></a>
                            {% endif %}
                            {% if contact_info.whatsapp %}
                                <a href="{{ contact_info.whatsapp }}"> <i class="fa fa-whatsapp"></i></a>
                            {% endif %}
                            {% if contact_info.twitter %}
                                <a href="{{ contact_info.twitter }}"> <i class="fa fa-twitter"></i></a>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </section>

        </div>
    </footer>

templates/includes/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'components/bootstrap/bootstrap-rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'components/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://use.fontawesome.com/96472d4340.js"></script>
</head>

templates/includes/header.html
{% load static %}
    <!-- top-header -->
    <div class="shadow position-fixed w-100 h-100 d-md-none d-lg-none"></div>
    <!-- top-header -->
    <header class="position-relative">
        <div class="main-header position-relative">

            <div class="nav-header-box mob1 d-md-flex d-lg-flex align-items-center justify-content-between">

                <div class="d-flex flex-column flex-md-row align-items-center pr-md-4">
                    <div class="logo d-flex justify-content-center align-items-center ml-3">
                        <a href="{% url 'home:home' %}"><img src="{% static 'image/logo.png' %}" class="logo-img img-fluid" alt="" /></a>
                    </div>
                    <form action="{% url 'videos:search result' %}" method="get">
                        <div class="nav-search-btn">
                        <input type="search" name="q" placeholder="جستجو">
                        <button type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                    </form>

                </div>
                <div class="d-block d-md-flex align-items-center pl-md-4">
                    <div class="dropdown notification-box">
                        <div class="position-relative d-none d-md-block " type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static 'image/notification.png' %}" class="notification-img" alt="">
                            {% if status %}
                                <div class="badge">{{ notif_count }}</div>
                            {% endif %}
                        </div>
                        <div class="dropdown-menu notification-menu-items custom-bg"
                            aria-labelledby="dropdownMenuButton">
                        {% if status %}
                            {% for notif in unread_notifs %}
                                {% if notif.n_post_id != -1 %}
                                <a class="border-bottom" href="{% url 'videos:read_notification' notif.n_post_id %}">
                                    نظر جدید از {{ notif.n_sender.full_name }}
                                    {{ notif.jalali_created }}
                                </a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                            {% for notif in read_notifications %}
                                <a class="border-bottom">
                                    {% if notif.n_post_id != -1 %}
                                         نظر جدید از {{ notif.sender.full_name }}
                                        {{ notif.jalali_created }}
                                    {% endif %}
                                </a>
                            {% endfor %}

                        </div>
                    </div>

                    <div class="header-login d-none d-md-block">

                        <div class="notification-box dropdown">
                            <a href="" class="btn login-btn" type="button" id="dropdownMenuButton"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if request.user.is_authenticated %}
                                    {% if request.user.image %}
                                        <img src="{{ request.user.image.url }}" alt="{{ request.user.username }}">
                                    {% else %}
                                        <img src="{% static 'image/sutdent-prof.png' %}" alt="{{ request.user.username }}">
                                    {% endif %}
                                {% else %}
                                    <span class="prepend-icon ml-1">
                                        <i class="fa fa-user-circle"></i>
                                    </span> <span>حساب کاربری </span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu account-menu-items custom-bg"
                                aria-labelledby="dropdownMenuButton">
                                {% if request.user.is_authenticated %}
                                    <a class="" href="{% url 'account:profile' request.user.id request.user.username %}"> پروفایل</a>
                                    <a class="" href="{% url 'videos:favorites' %}"> مورد علاقه ها</a>
                                    <a class="" href="{% url 'account:log out' %}"> خروج</a>
                                {% else %}
                                    <a class="" href="{% url 'account:log in' %}"> <i class=" fa fa-account"></i>
                                    ورود</a>
                                    <a class="" href="{% url 'account:register' %}"> ثبت نام</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <nav class="nav-menu p-0 m-0 d-flex d-sm-flex d-md-none d-lg-none">
                    <li id="" class="mx-3"><a class="nav-menu-item-mob">زبان های برنامه نویسی
                        <i class="fa fa-chevron-left chev-icon pr-1"></i>
                        </a>
                        <ul class="sub-menu-mob">
                            <a href="">جاوا</a>
                            <a href="">پایتون </a>
                            <a href="">آیتم</a>
                            <a href=""> آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                        </ul>
                    </li>
                    <li id="" class="mx-3"><a class="nav-menu-item-mob ">فریمورک
                        <i class="fa fa-chevron-left chev-icon pr-1"></i>
                        </a>
                        <ul class="sub-menu-mob">
                            <a href="">جاوا</a>
                            <a href="">پایتون </a>
                            <a href="">آیتم</a>
                            <a href=""> آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                        </ul>
                    </li>
                    <li id="" class="mx-3">
                        <a class="nav-menu-item-mob ">طراحی وب
                            <i class="fa fa-chevron-left chev-icon pr-1"></i>
                        </a>
                        <ul class="sub-menu-mob">
                            <a href="">جاوا</a>
                            <a href="">پایتون </a>
                            <a href="">آیتم</a>
                            <a href=""> آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                        </ul>
                    </li>
                    <li id="" class="mx-3"><a class="nav-menu-item-mob">زبان های برنامه نویسی
                        <i class="fa fa-chevron-left chev-icon pr-1"></i>
                        </a>
                        <ul class="sub-menu-mob">
                            <a href="">جاوا</a>
                            <a href="">پایتون </a>
                            <a href="">آیتم</a>
                            <a href=""> آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                            <a href="">آیتم</a>
                        </ul>
                    </li>

                </nav>

            </div>


            <section
                class="nav-header-box-mob d-flex d-sm-flex d-md-none  align-items-center justify-content-between d-md-none d-lg-none position-fixed">

                <div class="hamburger-icon">
                    <div class="bar1"></div>
                    <div class="bar2"></div>
                    <div class="bar3"></div>
                </div>
                <div class="logo">
                    <a href="index.html"><img src="{% static 'image/logo.png' %}" class="logo-img img-fluid" alt="" /></a>
                </div>

                <div class="d-flex align-items-center">
                    <div class="dropdown notification-box">
                        <div class="position-relative d-block d-md-none " type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static 'image/notification.png' %}" class="notification-img" alt="">
                            <div class="badge">2</div>
                        </div>
                        <div class="dropdown-menu notification-menu-items custom-bg"
                            aria-labelledby="dropdownMenuButton">
                            <a class="border-bottom" href="#"> ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ </a>
                            <a class="border-bottom" href="#"> ایپسوم متن ساختگی با تولید </a>
                            <a class="border-bottom" href="#"> ایپسوم متن ساختگی با تولید سادگی</a>

                        </div>
                    </div>

                    <div class="header-account">
                        <div class="notification-box dropdown">
                            <a href="" class="btn login-btn" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="{% static 'image/sutdent-prof.png' %}" alt="">
                            </a>
                            <div class="dropdown-menu account-menu-items custom-bg"
                                aria-labelledby="dropdownMenuButton">
                                <a class="" href="login.html"> <i class=" fa fa-account"></i>
                                    ورود</a>
                                <a class="" href="register.html"> ثبت نام</a>
                                <a class="" href="user-panel.html"> پروفایل</a>
                                <a class="" href="#"> مورد علاقه ها</a>
                                <a class="" href="#"> خروج</a>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div>

    </header>

    <nav class="nav-menu nav-menu-pc  d-none d-md-flex px-4" id="navbar">
        {% for cat in categories %}
            {% if cat.parent == None %}
                <li id="" class="mx-3 menu-item"><a href="{{ cat.get_absolute_url }}" class="nav-menu-item ">{{ cat.title }}</a>
                    {% if cat.children.all %}
                        <ul class="sub-menu">
                            {% for cat in cat.children.all %}
                                <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>
                            {% endfor %}
                        </ul>
                     {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </nav>

templates/includes/scripts.html
{% load static %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="{% static 'components/bootstrap/bootstrap.bundle.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

    <script src="{% static 'components/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'components/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'components/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/like-system.js' %}"></script>
    <script>
        // video-player
        const videobtn = document.querySelector('.video-btn');
        const video = document.querySelector('.video');
        const videotag = document.querySelector('video')
        const videoDescription = document.querySelector('.video-description')
        const closeBtn = document.querySelector('.close-btn')
        const videoPoster = document.querySelector('.video-poster')
        const videoOverlay = document.querySelector('.video-overlay')
        function stopPlayer() {
            videobtn.style.display = "block";
            closeBtn.style.display = 'none';
            videoPoster.style.display = 'inline'
            video.style.zIndex = '-1'
            videotag.pause()
            videotag.style.borderRadius = '20px'
            videoDescription.style.display = 'flex'
            videotag.controls = false
            videotag.style.borderRadius = '15px'
            videoOverlay.style.display = 'block'
        };

        function playvideo() {
            videobtn.style.display = "none";
            video.style.zIndex = '22222'
            videotag.autoplay = true
            videotag.play()
            videotag.style.borderRadius = '20px'
            videotag.controls = true
            videoDescription.style.display = 'none'
            closeBtn.style.display = 'block'
            videoPoster.style.display = 'none'
            videoOverlay.style.display = 'none'
        }
    </script>